{{- if .Values.installCRDs }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: talosworkers.talos.alperen.cloud
spec:
  group: talos.alperen.cloud
  names:
    kind: TalosWorker
    listKind: TalosWorkerList
    plural: talosworkers
    singular: talosworker
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TalosWorker is the Schema for the talosworkers API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TalosWorkerSpec defines the desired state of TalosWorker.
            properties:
              configRef:
                description: Reference to a ConfigMap containing the Talos cluster
                  configuration
                properties:
                  key:
                    description: The key to select.
                    type: string
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                  optional:
                    description: Specify whether the ConfigMap or its key must be
                      defined
                    type: boolean
                required:
                - key
                type: object
                x-kubernetes-map-type: atomic
              controlPlaneRef:
                description: ControlPlaneRef is a reference to the TalosControlPlane
                  that this worker belongs to
                format: objectreference
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              kubeVersion:
                default: v1.33.1
                description: KubeVersion is the version of Kubernetes to use for the
                  control plane
                pattern: ^v\d+\.\d+\.\d+(-\w+)?$
                type: string
                x-kubernetes-validations:
                - message: KubeVersion can not be decreased
                  rule: self >= oldSelf
              metalSpec:
                description: Metal Spec is required when mode is 'metal'
                properties:
                  machineSpec:
                    description: MachineSpec defines the specifications for each Talos
                      control plane machine.
                    properties:
                      additionalConfig:
                        description: AdditionalConfig is additional Talos configuration
                          to append to the generated config.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      airGap:
                        default: false
                        description: AirGap indicates whether the machine is in an
                          air-gapped environment.
                        type: boolean
                      allowSchedulingOnControlPlanes:
                        default: false
                        description: AllowSchedulingOnControlPlanes indicates whether
                          to allow scheduling workloads on control plane nodes.
                        type: boolean
                      image:
                        description: Image is the Talos image to use for this machine.
                        type: string
                      imageCache:
                        default: false
                        description: ImageCache indicates whether to enable local
                          image caching on the machine.
                        type: boolean
                      installDisk:
                        description: InstallDisk is the disk to use for installing
                          Talos on the control plane machines.
                        pattern: ^/dev/(sd[a-z][0-9]*|vd[a-z][0-9]*|nvme[0-9]+n[0-9]+(p[0-9]+)?)$
                        type: string
                      meta:
                        description: Meta is the meta partition that used by Talos.
                        properties:
                          dnsServers:
                            description: DNS Servers is a list of DNS servers for
                              the Talos machines.
                            items:
                              type: string
                            type: array
                          gateway:
                            description: Gateway is the gateway for the Talos machines.
                            type: string
                          hostname:
                            description: Hostname is the hostname for the Talos machines.
                            type: string
                          interface:
                            description: Interface is the network interface name for
                              Talos machines.
                            type: string
                          subnet:
                            description: Subnet is the subnet for the Talos machines.
                            type: integer
                        type: object
                      registries:
                        description: Registries is the path to a custom registries
                          configuration file.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      wipe:
                        default: false
                        description: Wipe indicates whether to wipe the disk before
                          installation.
                        type: boolean
                    type: object
                  machines:
                    description: Machines is a list of machine specifications for
                      the Talos control plane.
                    items:
                      properties:
                        address:
                          description: Address is the IP address of the Talos machine.
                          pattern: ^(\d{1,3}\.){3}\d{1,3}$
                          type: string
                        machineRef:
                          description: MachineRef is a reference to a Kubernetes object
                            from which the machine IP address can be extracted.
                          properties:
                            apiVersion:
                              description: APIVersion of the referenced object.
                              type: string
                            fieldPath:
                              description: FieldPath is the field path within the
                                referenced object.
                              type: string
                            kind:
                              description: Kind of the referenced object.
                              type: string
                            name:
                              description: Name of the referenced object.
                              type: string
                            namespace:
                              description: Namespace of the referenced object.
                              type: string
                          type: object
                      type: object
                      x-kubernetes-validations:
                      - message: address and machineRef are mutually exclusive
                        rule: has(self.address) != has(self.machineRef)
                    type: array
                type: object
              mode:
                enum:
                - container
                - metal
                - cloud
                type: string
              replicas:
                default: 1
                description: Number of control-plane machines to maintain
                format: int32
                minimum: 1
                type: integer
              storageClassName:
                description: StorageClassName is the name of the storage class to
                  use for persistent volumes
                pattern: ^[a-zA-Z0-9][-a-zA-Z0-9_.]*[a-zA-Z0-9]$
                type: string
                x-kubernetes-validations:
                - message: StorageClassName is immutable, you cannot change it after
                    creation
                  rule: self == oldSelf
              version:
                default: v1.33.1
                description: Version of Talos to use for the control plane(controller-manager,
                  scheduler, kube-apiserver, etcd) -- e.g "v1.33.1"
                pattern: ^v\d+\.\d+\.\d+(-\w+)?$
                type: string
            required:
            - kubeVersion
            - mode
            - replicas
            - version
            type: object
            x-kubernetes-validations:
            - message: MetalSpec is required when mode 'metal'
              rule: self.mode!='metal' || has(self.metalSpec)
          status:
            description: TalosWorkerStatus defines the observed state of TalosWorker.
            properties:
              conditions:
                description: |-
                  INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              config:
                type: string
              imported:
                description: Imported is only valid when ReconcileMode is 'import'
                  and indicates whether the Talos control plane has been imported
                type: boolean
              state:
                description: State represents the current state of the Talos worker
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
