# This rule is not used by the project talos-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to talos.alperen.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: talos-operator
    app.kubernetes.io/managed-by: kustomize
  name: talosclusteraddonrelease-viewer-role
rules:
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusteraddonreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusteraddonreleases/status
  verbs:
  - get
