# This rule is not used by the project talos-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over talos.alperen.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: talos-operator
    app.kubernetes.io/managed-by: kustomize
  name: talosclusteraddonrelease-admin-role
rules:
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusteraddonreleases
  verbs:
  - '*'
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusteraddonreleases/status
  verbs:
  - get
