apiVersion: talos.alperen.cloud/v1alpha1
kind: TalosClusterAddonRelease
metadata:
  labels:
    app.kubernetes.io/name: talos-operator
    app.kubernetes.io/managed-by: kustomize
  name: talosclusteraddonrelease-sample
spec:
  # TODO(user): Add fields here
