apiVersion: talos.alperencelik.dev/v1alpha1
kind: TalosControlPlane
metadata:
  name: taloscontrolplane-cloud-sample
spec:
  replicas: 3
  version: v1.5.0
  mode: cloud
  cloudSpec:
    gcp:
      project: my-gcp-project
      region: us-central1
      zone: us-central1-a
      instanceType: e2-medium
      image: projects/talos-linux/global/images/talos-v1-5-0
      network: default
      subnetwork: default
      tags:
        - talos-controlplane